#!/usr/bin/env python3
"""Generate a synthetic-but-realistic Malaysia 4D historical dataset.

The output mimics the real draw calendar of the three main operators:

  * Magnum 4D      (code M) - draws Wed / Sat / Sun
  * Da Ma Cai 1+3D (code D) - draws Wed / Sat / Sun
  * Sports Toto 4D (code T) - draws Wed / Sat / Sun

plus the occasional "special draw" Tuesdays that the operators run
(roughly one or two Tuesdays a month).

Each draw carries the full 23-number prize structure:
  1st, 2nd, 3rd prize, 10 special prizes, 10 consolation prizes.

Numbers are drawn uniformly at random WITHOUT replacement within a draw,
which matches how the real games behave statistically (each draw's 23
winning numbers are distinct).  A fixed RNG seed keeps the dataset
reproducible.

IMPORTANT: this is SAMPLE data for developing/demoing the app.  Replace
data/draws.json with real scraped history (see scrapers/) before relying
on any statistics.

Usage:
    python3 tools/generate_sample_data.py [--years 5.5] [--out data/draws.json]
"""

import argparse
import datetime as dt
import json
import random

OPERATORS = {
    "M": "Magnum 4D",
    "D": "Da Ma Cai 1+3D",
    "T": "Sports Toto 4D",
}

REGULAR_DRAW_WEEKDAYS = {2, 5, 6}  # Wed=2, Sat=5, Sun=6 (Python weekday())


def draw_numbers(rng: random.Random) -> dict:
    """Pick 23 distinct 4-digit numbers for one draw."""
    picks = rng.sample(range(10000), 23)
    fmt = [f"{n:04d}" for n in picks]
    return {"p": fmt[0:3], "s": fmt[3:13], "c": fmt[13:23]}


def build(years: float, seed: int, end: dt.date) -> dict:
    rng = random.Random(seed)
    start = end - dt.timedelta(days=round(years * 365.25))

    # Pre-pick special-draw Tuesdays: ~18 per year, shared by all operators
    # (the real special draws are gazetted for all operators on the same day).
    special_tuesdays = set()
    day = start
    while day <= end:
        if day.weekday() == 1 and rng.random() < 0.35:
            special_tuesdays.add(day)
        day += dt.timedelta(days=1)

    draws = []
    seq = {code: 5000 for code in OPERATORS}  # arbitrary starting draw numbers
    day = start
    while day <= end:
        is_regular = day.weekday() in REGULAR_DRAW_WEEKDAYS
        if is_regular or day in special_tuesdays:
            for code in OPERATORS:
                seq[code] += 1
                rec = {
                    "o": code,
                    "d": day.isoformat(),
                    "n": f"{seq[code]}/{day.strftime('%y')}",
                }
                rec.update(draw_numbers(rng))
                if not is_regular:
                    rec["x"] = 1  # special draw marker
                draws.append(rec)
        day += dt.timedelta(days=1)

    return {
        "schema": "my4d-draws-v1",
        "source": "synthetic-sample",
        "generated": dt.date.today().isoformat(),
        "note": (
            "SAMPLE DATA generated by tools/generate_sample_data.py. "
            "Replace with real scraped history before trusting statistics."
        ),
        "operators": OPERATORS,
        "draws": draws,
    }


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--years", type=float, default=5.5)
    ap.add_argument("--seed", type=int, default=4444)
    ap.add_argument("--end", type=str, default=None,
                    help="last draw date (YYYY-MM-DD), default: most recent Wed/Sat/Sun")
    ap.add_argument("--out", type=str, default="data/draws.json")
    args = ap.parse_args()

    if args.end:
        end = dt.date.fromisoformat(args.end)
    else:
        end = dt.date.today()
        while end.weekday() not in REGULAR_DRAW_WEEKDAYS:
            end -= dt.timedelta(days=1)

    payload = build(args.years, args.seed, end)
    with open(args.out, "w") as fh:
        json.dump(payload, fh, separators=(",", ":"))
    print(f"wrote {args.out}: {len(payload['draws'])} draws "
          f"({payload['draws'][0]['d']} .. {payload['draws'][-1]['d']})")


if __name__ == "__main__":
    main()
